### ISSUE TITLE
Replacement of relation in criteria condition not precise enough.

### ISSUE THREAD

**Issue by mdeweerd** [mdeweerd/yii-relatedsearchbehavior#4]
@LeoZandvliet 

After integrating  your recent update, I got a failure suring a search.

![image](https://user-images.githubusercontent.com/1504752/121683569-d8cee700-cabd-11eb-983c-58422b6379d9.png)

I instrumented the code like this:
```php
            // d. If a relation is used in the criteria condition, require it and adjust the condition
            // Pattern to search for, search if relation is used as whole word only (dont want partials to be replaced)
            $pattern = '/\b('.preg_quote($var).')\b/';
            if(preg_match($pattern, $criteria->condition)){
                $totalReplaced = 0;
                $require_relation=($shortrelation!=='');
$before=$criteria->condition;
                $criteria->condition = preg_replace($pattern, $column,$criteria->condition, -1, $totalReplaced);
$after=$criteria->condition;
throw new CException("BEFORE:$before\nAFTER:$after\nPATTERN:$pattern\nSHORTR:$shortrelation");
            }
```

`displayname` is a relation field but in the condition it is already expanded and quoted.  As  you can see this results in an unwanted replacement.

The regex needs to be improved to take into account quotes and fields of tables when specified already.

**Comment by mdeweerd** [comment]
Fixed in e4c929d

**Comment by LeoZandvliet** [comment]
Heya,

- how is your relatedSearch configuration for `displayname`?

In my case, but that's just how I learned myself to use your relatedSearchBehavior, I never name the relatedSearch to something existing.
For example in `post` you can search for `author.name`, I define it in the behavior as:

```
'author__name' => 'author.name'
```
So when writing my code to replace the `$criteria->condition` I never realised this can be quite troublesome if this naming convention isn't followed :)

I already encountered troubles in multiple objects with relations with the same relation name. For example an order with a status, and an orderLine with a status, joining them all together is a problem. So I call the status of the orderLine the lineStatus.

**Comment by mdeweerd** [comment]
In principle I reference columns of a table by preceding them with the table name or alias to avoid name clashes.

The idea behind using the same related name as the field name is that I can think of the related field as if it were a field of the "root" record.  Changing names at every level is making it more complex to track.

Of course in some cases, like the orderLine example, you need to have a different "related" alias.

I do have cases where I have an object that is linked to an owner that are both "entities" in the database.  In this case, the object has a "owner_name" related_field to reference the name field of the owner entity, where the object itself has a similar name_field.
But for a zipcode for instance that would be in the "address" table references for a given user, then I prefer to use the same name for the relation_alias as for the actual address field name.

**Comment by mdeweerd** [comment]
Extra update in f5e60f6 to allow spaces in SQL statement.
